### ISSUE TITLE
Cannot see File Name Hook under Pre Receive hooks anymore

### ISSUE THREAD

**Issue by jsangra** [christiangalsterer/stash-filehooks-plugin#34] opened 2017-11-14 05:49 UTC
It seems File Name Hook can only be used under Merge Checks with the last 2 releases. Is there a way to use it again under a Pre Receive hook?

**Comment by christiangalsterer** [comment] 2017-11-18 22:09
Duplicate of #32

**Closed as completed by christiangalsterer** 2017-11-18 22:09 UTC
