### ISSUE TITLE
.js file got rejected when Pattern used doesnot specify that.

### ISSUE THREAD

**Issue by nss373** [christiangalsterer/stash-filehooks-plugin#12] opened 2016-01-21 16:18 UTC
Hi,

We need to reject .jar, .war, .ear, .zip and .class  files.
I used the Pattern    .jar|.war|.ear|.zip|.class 
When we commit .js file , it also got rejected. Also some html files too.

Is there any problem in Pattern

**Comment by christiangalsterer** [comment] 2016-01-21 19:05
Which version do you use?

**Comment by nss373** [comment] 2016-01-21 19:48
Plugin version :  1.1.0
Stash/Bitbucket version : 3.11.0

**Comment by christiangalsterer** [comment] 2016-01-22 16:55
Hi @nss373,

I can't reproduce the problem. Can you please provide the following details
- exact path and file names of files committed
- sequence of commit + push commands

**Comment by nss373** [comment] 2016-01-26 17:13
We added a new rule added to our project in Stash which should restrict  files with the name patterns [.jar|.war|.ear|.zip|.dll|.class] from being pushed out to the remote branch.
Unfortunately this rule also seems to be blocking files with .png and .classpath extensions.

Atlassian Stash Version: 3.11.0
Plugin version: 1.1.0

**Comment by christiangalsterer** [comment] 2016-01-26 17:21
Can you provide the details to my previous question? In addition can you please provide the git error message you get when pushing the changes.

**Comment by raspy** [comment] 2017-05-09 12:26
Please remember that . in regex matches any character, not a dot only; you would need to escape it as \\. As such this pattern would match anywhere in the file name as it is not anchored, so for example files named 'to_be_aware.html' or 'foo.classpath' will match.

Please try to update your expression to:

(\\.jar|\\.war|\\.ear|\\.zip|\\.dll|\\.class)$

and see if this helps. You can also try one of many online regex checkers to validate your pattern against file names.

**Comment by christiangalsterer** [comment] 2017-07-23 11:37
Closed due to inactivity. Please reopen as needed.

**Closed as completed by christiangalsterer** 2017-07-23 11:37 UTC
